name: Frontend CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"] # 해당 브랜치로 PR이 올라올 때

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm" # npm 캐시를 사용하여 설치 속도 향상

      # 라이브러리 설치
      - name: Install dependencies
        run: npm install

      # 타입 체크
      - name: Type check
        run: npx tsc --noEmit

      # 린트 검사 (코드 스타일 및 문법 체크)
      - name: Lint check
        run: npm run lint

      # 단위 테스트
      - name: Unit test
        run: npm test

      # 빌드 테스트 (실제 배포용 파일 생성 확인)
      - name: Build project
        run: npm run build
